### ISSUE TITLE
Change the coordinate to pack.alpha in README

### ISSUE THREAD

**Issue by itsknk** [juxt/pack.alpha#100] opened 2022-02-17 04:25 UTC
Hey team, the coordinate in README has a wrong name compared to the actual repo name.
```
;; add this to :aliases:
:pack {:deps {io.github.juxt/pack {:git/sha "1a077d172afc94e7f7679ecaad57ed9b7dde687d"}}
       :ns-default juxt.pack.cli.api}
```

It should be:
```
;; add this to :aliases:
:pack {:deps {io.github.juxt/pack.alpha {:git/sha "1a077d172afc94e7f7679ecaad57ed9b7dde687d"}}
       :ns-default juxt.pack.cli.api}
```
If it's fine, I'd like to submit the PR for this tiny bit, or you can just change the repo name to `pack` from `pack.alpha`.

Cheers!

**Comment by RickMoynihan** [comment] 2022-03-24 12:51
dupe of #97

**Closed** 2022-03-24 13:51 UTC
